services:
  # SwiftCart Express Backend
  - type: web
    name: swiftcart-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          name: swiftcart-frontend
          type: web
          property: host   # <-- 'url' ko 'host' se replace kiya

  # SwiftCart Vite Frontend
  - type: web
    name: swiftcart-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: swiftcart-backend
          type: web
          property: host
          suffix: /api/v1
          # suffix: /api/v1 (Agar aap suffix lagate hain toh host ke aage jud jayega)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html